name: action

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Gradle Build and Upload"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build everything
        run: ./gradlew clean build --stacktrace

      - name: Upload all jars
        uses: actions/upload-artifact@v4
        with:
          name: "Gradle Build Artifacts"
          path: |
            **/build/libs/*.jar
            **/build/distributions/*.zip
            **/build/reports/tests/test/
